name: Release CE to DockerHub
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of kPow'
        required: true
      manifest:
        description: 'URL of Manifest'
        required: true
      release_number_bump:
        description: 'I have updated system.clj release number!'
        required: true
        default: 'false'

jobs:
  TagAndUpdateReleasesEdn:
    runs-on: ubuntu-latest
    name: Tag and update releases.edn
    steps:
      - uses: actions/checkout@v3

      - name: Check that we have bumped release number
        run: |
          ./scripts/release_number_check.sh ${{github.event.inputs.release_number_bump}}

      - name: Download and verify JAR(s)
        run: |
          ./scripts/jar.sh "${{github.event.inputs.manifest}}"

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      -
        # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: dockerfile/kpow-ce/Dockerfile 
          platforms: linux/amd64,linux/arm64
          push: true
          tags: factorhouse/kpow-ce:latest
