name: Update Docker Tag Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New version to set for the Docker image tags'
        required: true

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update Docker image tags in README.md
        run: |
          NEW_VERSION="${{ github.event.inputs.version }}"
          sed -i -E "s#(docker pull factorhouse/kpow:)[^\`]*#\1${NEW_VERSION}#" README.md
          sed -i -E "s#(docker pull factorhouse/kpow-ce:)[^\`]*#\1${NEW_VERSION}#" README.md

      - name: Commit and push README.md
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update Docker image tag to version ${{ github.event.inputs.version }}"
          git push origin main

  update-dockerhub-readme:
    needs: update-readme
    if: false # temporarily disabled
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Push dockerhub/kpow/README.md to Docker Hub (factorhouse/kpow)
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: factorhouse/kpow
          readme-filepath: ./dockerhub/kpow/README.md

      - name: Push dockerhub/kpow-ce/README.md to Docker Hub (factorhouse/kpow-ce)
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: factorhouse/kpow-ce
          readme-filepath: ./dockerhub/kpow-ce/README.md
